functionsDirectory = "C:\\Users\\Jeff\\Desktop\\New folder (2)\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[build]
publish = "C:\\Users\\Jeff\\Desktop\\New folder (2)"
publishOrigin = "config"
functions = "C:\\Users\\Jeff\\Desktop\\New folder (2)\\netlify\\functions"

[build.environment]
NODE_VERSION = "18"
PDF_RENDERER = "adobe"
SECRETS_SCAN_OMIT_KEYS = "SUPABASE_URL"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions.generate-capability-background]
external_node_modules = ["adm-zip"]

[functions."*"]
node_bundler = "esbuild"

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
from = "/privacy"
to = "/privacy.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/terms"
to = "/terms.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/sms-consent"
to = "/sms-consent.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/pipeline"
to = "/pipeline-dashboard.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/capgen"
to = "/capability-generator.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/apropos"
to = "/ag-dashboard.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/pro"
to = "/capgen-pro.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/pro/thankyou"
to = "/capgen-pro-thankyou.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/offer"
to = "/offer.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/welcome"
to = "/welcome.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/onboarding"
to = "/onboarding.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/signin"
to = "/onboarding.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/signup"
to = "/offer.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/demo"
to = "/demo.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/demo/snapshot"
to = "/demo-snapshot.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/capgen-onboarding"
to = "/capgen-onboarding.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/profile"
to = "/capgen-profile.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/opportunity"
to = "/opportunity.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/marketing-dashboard"
to = "/marketing-dashboard.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/member-home"
to = "/member-home.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]